version: "3.9"
services:

  database:
    image: postgres:14.0
    environment:
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - type: bind
        source: ./
        target: /docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"